### ISSUE TITLE
打开暗色模式，导航栏没有变暗

### ISSUE THREAD

**Issue by tqb-web** [rqh656418510/hexo-next-darkmode#3]
**为什么导航栏没有变暗呀？**
我的博客:tianqb.top

**Comment by rqh656418510** [comment]
以前有网友遇到过你说的问题，可以试试关闭博客的背景图片，观察一下问题是否依然存在。附上评论截图：

![image](https://user-images.githubusercontent.com/5085501/164885706-04dccd63-c01a-459c-b6fe-cfda2283b3ba.png)
